apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auto-scaler-name
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-name-to-which-you-want-to-point
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  
  
  