apiVersion: v1
kind: Service
metadata:
  name: back-end-pod-service

spec:
  selector:
   app: back-end

  ports:
    - name: http
      port: 60
      nodePort: 30010
      targetPort: 4000

  type: NodePort