apiVersion: v1
kind: Service
metadata:
  name: front-end-pod-service
spec:  
  selector:
    app: front-end

  ports:
    - name: http
      port: 80
      nodePort: 30090
      targetPort: 3000

  type: NodePort
